name: Nightly Unstable Build and Package

on:
  schedule:
    - cron: '0 1 * * *'  # Run every day at 1:00 AM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-test-unstable:
    uses: redis/docker-library-redis/.github/workflows/build-n-test.yml@unstable
    with:
      release_tag: unstable
      publish_image: true
      redisearch_version: master
      redisjson_version: master
      redisbloom_version: master
      redistimeseries_version: master
      run_type: nightly

